http:
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: false
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: false
        stsIncludeSubdomains: false
        stsPreload: false
        stsSeconds: 0
